### ISSUE TITLE
Crash with read-only root filesystem

### ISSUE THREAD

**Issue by uhthomas** [1Password/kubernetes-secrets-injector#45]
### Your environment

Secret Injector Version: 1.0.2

1Password CLI Version: N/A

Connect Server Version: N/A

Kubernetes Version: N/A

## What happened?

It's good security practice to set security contexts, specifically `readOnlyRootFilesystem`. However, the container will crash instantly when enabled.

## What did you expect to happen?

The container should run normally.

## Steps to reproduce

Set the container security context option `readOnlyRootFilesystem` to true.

## Notes & Logs

This is caused by [glog's default behaviour](https://github.com/golang/glog/blob/6b9d7f7df28d318a28dde3adb8a5e9ae9bf1abaf/glog.go#L38-L40) of writing to a temporary file. It can be disabled with the `logtostderr` flag, but glog never has the chance to read this flag as [flag.Parse](https://github.com/1Password/kubernetes-secrets-injector/blob/77d101e15325d9d8894657c6096b76378933de02/cmd/main.go#L36) is called after a [glog log](https://github.com/1Password/kubernetes-secrets-injector/blob/77d101e15325d9d8894657c6096b76378933de02/cmd/main.go#L32).

**Comment by ingridcrant** [comment]
Hey @uhthomas! I'm having trouble validating the glog behaviour as the source of the issue. Could you provide the steps that you used to confirm that the PR solves the issue?

**Comment by edif2008** [comment]
Closing this ticket as there was no response for a while. Feel free to re-open if the problem persists.

In the meantime, it was identified that the root cause of the issue you're facing is related to the fact that the CLI is trying to write in the `/tmp` and `/op` (or `.op`) directories. This is required by the CLI to properly handle authentication when using a service account with the CLI. The workaround that was found for the original issue is as follows:
1. Add the following snippet to the deployment in which the `kubernetes-secrets-injector` will inject secrets into:
   ```yaml
   spec:
     volumes:
       - name: tmp
          mountPath: /tmp/
       - name: op
          mountPath: /.op/
   ```
2. Re-apply the new configuration (it might require a restart).

Once this is done, It should work as expected.

**Comment by uhthomas** [comment]
> Hey @uhthomas! I'm having trouble validating the glog behaviour as the source of the issue. Could you provide the steps that you used to confirm that the PR solves the issue?

If you run it with a read-only file system, the first log line is never seen because glog can't initialise. It would be nice to merge this fix regardless of whether or not the rest of the app needs certain mounts. Let me know if you need help validating it.
